//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinhaApi.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FornecedorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FornecedorResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinhaApi.Business.Resources.FornecedorResource", typeof(FornecedorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrada não informada..
        /// </summary>
        public static string Entrada_Nao_Informada {
            get {
                return ResourceManager.GetString("Entrada_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor alterado com sucesso..
        /// </summary>
        public static string Fornecedor_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Fornecedor_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor cadastrado com sucesso..
        /// </summary>
        public static string Fornecedor_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Fornecedor_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este cnpj já existe no sistema..
        /// </summary>
        public static string Fornecedor_Cnpj_Ja_Existente {
            get {
                return ResourceManager.GetString("Fornecedor_Cnpj_Ja_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consulta realizada com sucesso..
        /// </summary>
        public static string Fornecedor_Consulta_Realizada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Fornecedor_Consulta_Realizada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor excluído com sucesso..
        /// </summary>
        public static string Fornecedor_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Fornecedor_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID do fornecedor não encontrado..
        /// </summary>
        public static string Fornecedor_ID_Nao_Encontrado {
            get {
                return ResourceManager.GetString("Fornecedor_ID_Nao_Encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor obtido com sucesso..
        /// </summary>
        public static string Fornecedor_Obtido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Fornecedor_Obtido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum fornecedor encontrado..
        /// </summary>
        public static string Nenhum_Fornecedor_Encontrado {
            get {
                return ResourceManager.GetString("Nenhum_Fornecedor_Encontrado", resourceCulture);
            }
        }
    }
}
